apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-new-name
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nanajanashia/argocd-app:1.1
          ports:
            - containerPort: 8080
